version: "1"
services:
  mysql:
    image: mysql:latest
    container_name: mini-bbs-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "5051:5051"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER_ID}"
      MYSQL_PASSWORD: "${DB_USER_PASSWORD}"
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: mini-bbs-db-adminer
    restart: always
    ports:
      - "5052:8080" # adminer의 기본 포트 8080은 고정이다